### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by chippinkston** [framework-one/fw1-commands#4]
This is a fairly small thing, but I ran into this on Linux - and it may impact Mac users as well:

```
$> fw1 create app fooApp subsystem
ERROR
The app skeleton [/home/chip/.CommandBox/cfml/modules/fw1-commands/resources/skeletons/subsystem.zip] doesn't exist. Valid options are Subsystem, Examples, Skeleton, Basic, Subsystem-Legacy.
```

It worked when I re-ran the command and updated the case to:
    `$>  fw1 create app fooApp Subsystem`

Easy enough to fix here, but case sensitivity may be an issue elsewhere.

**Comment by tonyjunkes** [comment]
Nice catch. I'll look it over and get that straightened out.

**Comment by tonyjunkes** [comment]
This should be resolved now from this commit https://github.com/framework-one/fw1-commands/commit/129e009a5ddc607ec911518e3845b6730a0ed564
