### ISSUE TITLE
Default created subsystem configuration is invalid

### ISSUE THREAD

**Issue by seancorfield** [framework-one/fw1-commands#6]
This command:

    box fw1 create app MyApp subsystem new/test

produces a skeleton app with this in the FW/1 configuration:

    subsystems = {
        module = ''
    }

It's illegal for the configuration to be a string -- it needs to be a struct:

    subsystems = {
        module = { }
    }

**Comment by tonyjunkes** [comment]
I may have caught this in a local fix I haven't pushed yet as it looks familiar now that you raise it. I'll make time to tackle this as I wanted to make an effort to push some updates this weekend.
